# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Tue Dec 22 00:07:40 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grpTelescopeControl = QtWidgets.QGroupBox(self.centralwidget)
        self.grpTelescopeControl.setObjectName("grpTelescopeControl")
        self.gridLayout = QtWidgets.QGridLayout(self.grpTelescopeControl)
        self.gridLayout.setObjectName("gridLayout")
        self.btnHdgNeg3 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnHdgNeg3.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnHdgNeg3.setObjectName("btnHdgNeg3")
        self.gridLayout.addWidget(self.btnHdgNeg3, 0, 0, 1, 1)
        self.btnHdgNeg2 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnHdgNeg2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnHdgNeg2.setObjectName("btnHdgNeg2")
        self.gridLayout.addWidget(self.btnHdgNeg2, 0, 1, 1, 1)
        self.btnHdgNeg1 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnHdgNeg1.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnHdgNeg1.setObjectName("btnHdgNeg1")
        self.gridLayout.addWidget(self.btnHdgNeg1, 0, 2, 1, 1)
        self.vbxHdg = QtWidgets.QVBoxLayout()
        self.vbxHdg.setObjectName("vbxHdg")
        self.lblHdg = QtWidgets.QLabel(self.grpTelescopeControl)
        self.lblHdg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHdg.setObjectName("lblHdg")
        self.vbxHdg.addWidget(self.lblHdg)
        self.edtHdg = QtWidgets.QLineEdit(self.grpTelescopeControl)
        self.edtHdg.setText("")
        self.edtHdg.setAlignment(QtCore.Qt.AlignCenter)
        self.edtHdg.setObjectName("edtHdg")
        self.vbxHdg.addWidget(self.edtHdg)
        self.gridLayout.addLayout(self.vbxHdg, 0, 3, 1, 1)
        self.btnHdgPos1 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnHdgPos1.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnHdgPos1.setObjectName("btnHdgPos1")
        self.gridLayout.addWidget(self.btnHdgPos1, 0, 4, 1, 1)
        self.btnHdgPos2 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnHdgPos2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnHdgPos2.setObjectName("btnHdgPos2")
        self.gridLayout.addWidget(self.btnHdgPos2, 0, 5, 1, 1)
        self.btnHdgPos3 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnHdgPos3.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnHdgPos3.setObjectName("btnHdgPos3")
        self.gridLayout.addWidget(self.btnHdgPos3, 0, 6, 1, 1)
        self.btnLatNeg3 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnLatNeg3.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnLatNeg3.setObjectName("btnLatNeg3")
        self.gridLayout.addWidget(self.btnLatNeg3, 1, 0, 1, 1)
        self.btnLatNeg2 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnLatNeg2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnLatNeg2.setObjectName("btnLatNeg2")
        self.gridLayout.addWidget(self.btnLatNeg2, 1, 1, 1, 1)
        self.btnLatNeg1 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnLatNeg1.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnLatNeg1.setObjectName("btnLatNeg1")
        self.gridLayout.addWidget(self.btnLatNeg1, 1, 2, 1, 1)
        self.vbxLat = QtWidgets.QVBoxLayout()
        self.vbxLat.setObjectName("vbxLat")
        self.lblLat = QtWidgets.QLabel(self.grpTelescopeControl)
        self.lblLat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLat.setObjectName("lblLat")
        self.vbxLat.addWidget(self.lblLat)
        self.edtLat = QtWidgets.QLineEdit(self.grpTelescopeControl)
        self.edtLat.setText("")
        self.edtLat.setAlignment(QtCore.Qt.AlignCenter)
        self.edtLat.setObjectName("edtLat")
        self.vbxLat.addWidget(self.edtLat)
        self.gridLayout.addLayout(self.vbxLat, 1, 3, 1, 1)
        self.btnLatPos1 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnLatPos1.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnLatPos1.setObjectName("btnLatPos1")
        self.gridLayout.addWidget(self.btnLatPos1, 1, 4, 1, 1)
        self.btnLatPos2 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnLatPos2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnLatPos2.setObjectName("btnLatPos2")
        self.gridLayout.addWidget(self.btnLatPos2, 1, 5, 1, 1)
        self.btnLatPos3 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnLatPos3.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnLatPos3.setObjectName("btnLatPos3")
        self.gridLayout.addWidget(self.btnLatPos3, 1, 6, 1, 1)
        self.btnRANeg3 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnRANeg3.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnRANeg3.setObjectName("btnRANeg3")
        self.gridLayout.addWidget(self.btnRANeg3, 2, 0, 1, 1)
        self.btnRANeg2 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnRANeg2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnRANeg2.setObjectName("btnRANeg2")
        self.gridLayout.addWidget(self.btnRANeg2, 2, 1, 1, 1)
        self.btnRANeg1 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnRANeg1.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnRANeg1.setObjectName("btnRANeg1")
        self.gridLayout.addWidget(self.btnRANeg1, 2, 2, 1, 1)
        self.vbxRA = QtWidgets.QVBoxLayout()
        self.vbxRA.setObjectName("vbxRA")
        self.lblRA = QtWidgets.QLabel(self.grpTelescopeControl)
        self.lblRA.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRA.setObjectName("lblRA")
        self.vbxRA.addWidget(self.lblRA)
        self.edtRA = QtWidgets.QLineEdit(self.grpTelescopeControl)
        self.edtRA.setText("")
        self.edtRA.setAlignment(QtCore.Qt.AlignCenter)
        self.edtRA.setObjectName("edtRA")
        self.vbxRA.addWidget(self.edtRA)
        self.gridLayout.addLayout(self.vbxRA, 2, 3, 1, 1)
        self.btnRAPos1 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnRAPos1.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnRAPos1.setObjectName("btnRAPos1")
        self.gridLayout.addWidget(self.btnRAPos1, 2, 4, 1, 1)
        self.btnRAPos2 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnRAPos2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnRAPos2.setObjectName("btnRAPos2")
        self.gridLayout.addWidget(self.btnRAPos2, 2, 5, 1, 1)
        self.btnRAPos3 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnRAPos3.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnRAPos3.setObjectName("btnRAPos3")
        self.gridLayout.addWidget(self.btnRAPos3, 2, 6, 1, 1)
        self.btnDecNeg3 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnDecNeg3.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnDecNeg3.setObjectName("btnDecNeg3")
        self.gridLayout.addWidget(self.btnDecNeg3, 3, 0, 1, 1)
        self.btnDecNeg2 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnDecNeg2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnDecNeg2.setObjectName("btnDecNeg2")
        self.gridLayout.addWidget(self.btnDecNeg2, 3, 1, 1, 1)
        self.btnDecNeg1 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnDecNeg1.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnDecNeg1.setObjectName("btnDecNeg1")
        self.gridLayout.addWidget(self.btnDecNeg1, 3, 2, 1, 1)
        self.vbxDec = QtWidgets.QVBoxLayout()
        self.vbxDec.setObjectName("vbxDec")
        self.lblDec = QtWidgets.QLabel(self.grpTelescopeControl)
        self.lblDec.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDec.setObjectName("lblDec")
        self.vbxDec.addWidget(self.lblDec)
        self.edtDec = QtWidgets.QLineEdit(self.grpTelescopeControl)
        self.edtDec.setText("")
        self.edtDec.setAlignment(QtCore.Qt.AlignCenter)
        self.edtDec.setObjectName("edtDec")
        self.vbxDec.addWidget(self.edtDec)
        self.gridLayout.addLayout(self.vbxDec, 3, 3, 1, 1)
        self.btnDecPos1 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnDecPos1.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnDecPos1.setObjectName("btnDecPos1")
        self.gridLayout.addWidget(self.btnDecPos1, 3, 4, 1, 1)
        self.btnDecPos2 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnDecPos2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnDecPos2.setObjectName("btnDecPos2")
        self.gridLayout.addWidget(self.btnDecPos2, 3, 5, 1, 1)
        self.btnDecPos3 = QtWidgets.QPushButton(self.grpTelescopeControl)
        self.btnDecPos3.setMaximumSize(QtCore.QSize(48, 16777215))
        self.btnDecPos3.setObjectName("btnDecPos3")
        self.gridLayout.addWidget(self.btnDecPos3, 3, 6, 1, 1)
        self.horizontalLayout.addWidget(self.grpTelescopeControl)
        self.wdgTelescope = TelescopeWidget(self.centralwidget)
        self.wdgTelescope.setObjectName("wdgTelescope")
        self.horizontalLayout.addWidget(self.wdgTelescope)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.grpTelescopeControl.setTitle(QtWidgets.QApplication.translate("MainWindow", "Telescope control", None, -1))
        self.btnHdgNeg3.setText(QtWidgets.QApplication.translate("MainWindow", "<<<", None, -1))
        self.btnHdgNeg2.setText(QtWidgets.QApplication.translate("MainWindow", "<<", None, -1))
        self.btnHdgNeg1.setText(QtWidgets.QApplication.translate("MainWindow", "<", None, -1))
        self.lblHdg.setText(QtWidgets.QApplication.translate("MainWindow", "Heading", None, -1))
        self.btnHdgPos1.setText(QtWidgets.QApplication.translate("MainWindow", ">", None, -1))
        self.btnHdgPos2.setText(QtWidgets.QApplication.translate("MainWindow", ">>", None, -1))
        self.btnHdgPos3.setText(QtWidgets.QApplication.translate("MainWindow", ">>>", None, -1))
        self.btnLatNeg3.setText(QtWidgets.QApplication.translate("MainWindow", "<<<", None, -1))
        self.btnLatNeg2.setText(QtWidgets.QApplication.translate("MainWindow", "<<", None, -1))
        self.btnLatNeg1.setText(QtWidgets.QApplication.translate("MainWindow", "<", None, -1))
        self.lblLat.setText(QtWidgets.QApplication.translate("MainWindow", "Latitude", None, -1))
        self.btnLatPos1.setText(QtWidgets.QApplication.translate("MainWindow", ">", None, -1))
        self.btnLatPos2.setText(QtWidgets.QApplication.translate("MainWindow", ">>", None, -1))
        self.btnLatPos3.setText(QtWidgets.QApplication.translate("MainWindow", ">>>", None, -1))
        self.btnRANeg3.setText(QtWidgets.QApplication.translate("MainWindow", "<<<", None, -1))
        self.btnRANeg2.setText(QtWidgets.QApplication.translate("MainWindow", "<<", None, -1))
        self.btnRANeg1.setText(QtWidgets.QApplication.translate("MainWindow", "<", None, -1))
        self.lblRA.setText(QtWidgets.QApplication.translate("MainWindow", "RA", None, -1))
        self.btnRAPos1.setText(QtWidgets.QApplication.translate("MainWindow", ">", None, -1))
        self.btnRAPos2.setText(QtWidgets.QApplication.translate("MainWindow", ">>", None, -1))
        self.btnRAPos3.setText(QtWidgets.QApplication.translate("MainWindow", ">>>", None, -1))
        self.btnDecNeg3.setText(QtWidgets.QApplication.translate("MainWindow", "<<<", None, -1))
        self.btnDecNeg2.setText(QtWidgets.QApplication.translate("MainWindow", "<<", None, -1))
        self.btnDecNeg1.setText(QtWidgets.QApplication.translate("MainWindow", "<", None, -1))
        self.lblDec.setText(QtWidgets.QApplication.translate("MainWindow", "Declination", None, -1))
        self.btnDecPos1.setText(QtWidgets.QApplication.translate("MainWindow", ">", None, -1))
        self.btnDecPos2.setText(QtWidgets.QApplication.translate("MainWindow", ">>", None, -1))
        self.btnDecPos3.setText(QtWidgets.QApplication.translate("MainWindow", ">>>", None, -1))

from telescopewidget import TelescopeWidget
